[img]
cnodes = [ "value", "uncertainty" ]
wnodes = [ "tailx", "taily", "tailz", "headx", "heady", "headz" ]
bnodes = [
    "value", "uncertainty", "start", "span", "min1", "max1", "min2", "max2",
    "min3", "max3",
]
snodes = [ "value", "uncertainty", "start", "span" ]
mnodes = [ "value", "uncertainty" ]

[tru]
cnodes = []
wnodes = []
bnodes = [ "value", ]
snodes = []
mnodes = []
